name: Schedule Test

on:
  schedule:
    # Vamos forçar um minuto específico para o "acordar"
    # Agora são 13:34 UTC. Vamos marcar para as 13:40 UTC (14:40 Lisboa)
    - cron: "51 12 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: |
          echo "Teste de agendamento a correr..."
          date
          echo "Evento: ${{ github.event_name }}"
