name: Schedule Test

on:
  schedule:
    - cron: "*/5 * * * *"
      timezone: "Europe/Lisbon"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: |
          echo "Schedule test running"
          date -u
          echo "Event: ${{ github.event_name }}"
